### ISSUE TITLE
Missing menu items when not in Admin user

### ISSUE THREAD

**Issue by being-peace** [dorianim/modern-mrbs-theme#2]
When I am not logged in as admin, the modern theme (sourcecode from today) does not show any menu items.

https://user-images.githubusercontent.com/58709258/139510502-596bc138-713e-428c-b3d9-c3e0a32f1d22.mp4

**Comment by dorianim** [comment]
Hi! Sorry for not replying. Somehow I did not get a notification about this. Please test again with v0.3.0.

**Comment by being-peace** [comment]
Fixed by: https://github.com/dorianim/modern-mrbs-theme/pull/3
