### ISSUE TITLE
Importing does not work, when modern theme is activated

### ISSUE THREAD

**Issue by being-peace** [dorianim/modern-mrbs-theme#4]
Then using import.php with this theme, there are two issues:
1) The ajax to switch on and off inputs does not work. There should be displayed either the URL or the File
![grafik](https://user-images.githubusercontent.com/58709258/146855960-090701fd-940d-4f86-b839-0e154a533493.png)

2) When actually performing the import, nothing is done. The cause could be, that import.php uses a submit button with the name "import" and assumes that this is formed into a field. Without Bootstrap this works. But with Bootstrap - if I turn the POST into GET parameters - it does not work. The "import" parameter is not given here. Any idea?

**Comment by dorianim** [comment]
I have never tried the import to be honest. Could you supply me wth a file that should work?
The way mrbs handles this is just plain stupid, I have no idea why they are doing it like this.

**Comment by being-peace** [comment]
You can use any file, if you receive an error, it´s okay. :-) 
It seems that a hidden field with "import=true" would help for the second issue. But I don´t know, why booststrap does ignore the name="import" in the submit button.

**Comment by dorianim** [comment]
I need to dig a bit. I already had this exact problem in a different place.

**Comment by dorianim** [comment]
It works now, and I also added a nice error bar 
![image](https://user-images.githubusercontent.com/30153207/147213056-c96ba058-07f1-48fc-836c-891c9632a4da.png)
But I still need to implemement that switch

**Comment by dorianim** [comment]
Done :)

**Comment by being-peace** [comment]
Thanks, it works!!!
Yet, there is an switch on ignore_location.

```
  function() {
    var ignoreLocation = $(this).is(':checked');
    $('#location_parsing').toggle(!ignoreLocation);
    $('#ignore_location_settings').toggle(ignoreLocation);
  }
```

Why is it that all these things have to be reprogrammed explicitly in the new Theme? Does the jquery gets lost in the transformation?

**Comment by dorianim** [comment]
Please open another issue for that, ot I will forget about it 😅 
Unfortunately, the built in javascript of mrbs conflicted with some of the js of Bootstrap, so I had to throw it out completely.
