### ISSUE TITLE
Theme is not activated for unknown reasons

### ISSUE THREAD

**Issue by being-peace** [dorianim/modern-mrbs-theme#5]
I have two installations, one in a local docker image, one on a webhoster. The files should be identical.
On the one installation, the modern theme is activated. But on the webhoster, it is the standard theme.
Any idea?

**Comment by dorianim** [comment]
Maybe wrong file permissions?

**Comment by being-peace** [comment]
Thanks! With this hint, I looked at the right place. 
It were the symbolic links where the syncing process tried to be very clever and created wrong absolute files.
I don´t get, why symbolic links are necessary, but now I know what to do. lftp has a --dereference switch. :-)
