### ISSUE TITLE
Guide to install

### ISSUE THREAD

**Issue by khanhdn0112** [dorianim/modern-mrbs-theme#9]
Hi,
Could you guide me on how to install these themes to MRBS? 
I'm using MRBS on Windows Server and IIS.

Thank you so much

**Comment by dorianim** [comment]
Hi, 

the readme has a brief explanation:
https://github.com/dorianim/modern-mrbs-theme#usage

Do you have any specific questions about that?

**Comment by khanhdn0112** [comment]
> Hi,
> 
> the readme has a brief explanation: https://github.com/dorianim/modern-mrbs-theme#usage
> 
> Do you have any specific questions about that?

Hi,
Thank you for your support.
I alr added config as your guideline. but themes still not changed to new themes.
![image](https://github.com/dorianim/modern-mrbs-theme/assets/54300028/dd73ae64-1df4-4272-862b-0832f1c5b340)

![image](https://github.com/dorianim/modern-mrbs-theme/assets/54300028/c90b00e9-a9c8-4392-9b86-8e50d3f658e9)

![image](https://github.com/dorianim/modern-mrbs-theme/assets/54300028/8b41dbd0-e7cf-4223-aff3-0e37d6d88c6c)

What should I do?

**Comment by dorianim** [comment]
Have you copied the `modern` Folder from the Repo into the `Themes` Folder of your installation?

**Comment by khanhdn0112** [comment]
> Have you copied the `modern` Folder from the Repo into the `Themes` Folder of your installation?

Yes, I copied the modern folder from the Repo into the Themes folder.
![image](https://github.com/dorianim/modern-mrbs-theme/assets/54300028/7b1f7831-1918-4635-aef7-2663df8f2d93)

**Comment by dorianim** [comment]
Which version of mrbs are you using?

**Comment by dorianim** [comment]
Ohh, I see the issue. There are some symliks which don't work on Windows.
Please delete the files marked red and remove the `.php` suffix from the files marked green.
![image](https://github.com/dorianim/modern-mrbs-theme/assets/30153207/8c54dfc9-030a-42a8-b44d-7c56a5eb96cf)

**Comment by khanhdn0112** [comment]
> Ohh, I see the issue. There are some symliks which don't work on Windows. Please delete the files marked red and remove the `.php` suffix from the files marked green. ![image](https://private-user-images.githubusercontent.com/30153207/320926991-8c54dfc9-030a-42a8-b44d-7c56a5eb96cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTAzMDksIm5iZiI6MTcxMjcxMDAwOSwicGF0aCI6Ii8zMDE1MzIwNy8zMjA5MjY5OTEtOGM1NGRmYzktMDMwYS00MmE4LWI0NGQtN2M1NmE1ZWI5NmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAwNDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZGUzODBkZWE1ZjFlNDdiODE0YzRiMTkxOTY5YTZhOGQ4YjgxODA5NTQzMGFjMThhMmI3ODA2M2NhYmFmMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.585oYDmBKJ6qjqGd7lvFyqG4OlabAtvm6Gw6yzqZ85c)

Hi, I removed .php suffix in these files but facing an error as image below
![image](https://github.com/dorianim/modern-mrbs-theme/assets/54300028/aadbda57-f872-4d12-b727-5c522ae51c65)

**Comment by dorianim** [comment]
Try adding 
```
error_reporting(E_ERROR | E_PARSE);
```

To your config.php

**Comment by khanhdn0112** [comment]
> Try adding
> 
> ```
> error_reporting(E_ERROR | E_PARSE);
> ```
> 
> To your config.php

Hi, I've tried add to config.php but I'm still facing an error as below:
![image](https://github.com/dorianim/modern-mrbs-theme/assets/54300028/30c249c8-1abb-44f2-a0eb-fe71a0e4561e)

E_WARNING in C:\xampp\htdocs\mrbs\web\Themes\modern\header.inc at line 607
Undefined variable $view_week_number
MRBS GET: Array
(
)
MRBS POST: Array
(
)
MRBS SESSION: Array
(
    [csrf_token] => aaef990e485423eadc3ee5be6bd80bed506517d4d761684163f4dd21579e8301
    [user] => MRBS\User Object
        (
            [username] => admin
            [display_name] => admin
            [email] => khanh.dinh@gmail.com
            [level] => 2
            [data:protected] => Array
                (
                    [id] => 2
                    [password_hash] => $2y$10$JGl1cHi8JuJ3Pa1jwUyObOpm8n26drL2D7K8OwhqwM9t48e5aLv0u
                    [timestamp] => 2024-02-21 13:30:14
                    [last_login] => 1712734986
                    [reset_key_hash] =>
                    [reset_key_expiry] => 0
                )

        )

)

**Comment by dorianim** [comment]
Hmm, maybe try to disable error reproting in your php server.

**Comment by dyerry79** [comment]
> > Try adding
> > ```
> > error_reporting(E_ERROR | E_PARSE);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To your config.php
> 
> Hi, I've tried add to config.php but I'm still facing an error as below: ![image](https://private-user-images.githubusercontent.com/54300028/321149578-30c249c8-1abb-44f2-a0eb-fe71a0e4561e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1MTgxODAsIm5iZiI6MTcyODUxNzg4MCwicGF0aCI6Ii81NDMwMDAyOC8zMjExNDk1NzgtMzBjMjQ5YzgtMWFiYi00NGYyLWEwZWItZmU3MWEwZTQ1NjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDIzNTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3Nzk2Mjk1ZDM1N2FhMjBjOGVhNDI1YzNiNWI3ZTMwOWEyODBkOTA3YjVhNjkwM2U2MTcyNjgxNzkxMjkzNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2dut0wn4ySsV8lfGEecScVJl3XPkMnSMx8mA7c1Kbbw)
> 
> E_WARNING in C:\xampp\htdocs\mrbs\web\Themes\modern\header.inc at line 607 Undefined variable $view_week_number MRBS GET: Array ( ) MRBS POST: Array ( ) MRBS SESSION: Array ( [csrf_token] => aaef990e485423eadc3ee5be6bd80bed506517d4d761684163f4dd21579e8301 [user] => MRBS\User Object ( [username] => admin [display_name] => admin [email] => [khanh.dinh@gmail.com](mailto:khanh.dinh@gmail.com) [level] => 2 [data:protected] => Array ( [id] => 2 [password_hash] => $2y$10$JGl1cHi8JuJ3Pa1jwUyObOpm8n26drL2D7K8OwhqwM9t48e5aLv0u [timestamp] => 2024-02-21 13:30:14 [last_login] => 1712734986 [reset_key_hash] => [reset_key_expiry] => 0 )
> 
> ```
>     )
> ```
> 
> )

While trying to explore MRBS, I found this theme and experienced the same error as you mentioned. Since the warning is "Undefined variable $view_week_number", you need to include  $view_week_number at line 502 of the header.inc file

**Comment by dorianim** [comment]
Fixed in [v0.4.2](https://github.com/dorianim/modern-mrbs-theme/releases/tag/v0.4.2)
